version: '3'
services:
  app:
    build: '.'
    ports:
      - '8000:8000'
    links:
      - db
    environment:
      - "DB_USER=pantry"
      - "DB_PASS=secret"
      - "DB_HOST=db"
      - "DB_NAME=pantry"
      - "APP_PORT=9000"
  db:
    image: 'postgres'
    environment:
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=pantry"
      - "POSTGRES_DB=pantry"

