version: '3'
services:
  app:
    build: '.'
    ports:
      - '8000:80'
    depends_on:
      - db
    environment:
      - "DB_URL=postgres://pantry:secret@db/pantry"
      - "APP_PORT=80"
  db:
    image: 'postgres'
    environment:
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=pantry"
      - "POSTGRES_DB=pantry"

