apiVersion: v1
kind: Service
metadata:
  name: pantry-server-service
spec:
  selector:
    app: pantry
    role: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: LoadBalancer
