apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pantry-db-stateful-set
spec:
  selector:
    matchLabels:
      app: pantry
      role: db
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      app: pantry
      role: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: pantry-app-db
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: "secret"
            - name: POSTGRES_USER
              value: "pantry"
            - name: POSTGRES_DB
              value: "pantry"
  volumeClaimTemplates:
    - metadata:
        name: pantry-db-stateful-set
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "my-storage-class"
        resources:
          requests:
            storage: 1Gi
          
      
